# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Git\PoseLibrary\pylib\ui\poseLibrary_window.ui'
#
# Created: Thu Aug 16 10:48:14 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font: 14pt \"MS Sans Serif\";")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeWidget_folderList = QtWidgets.QTreeWidget(self.splitter)
        self.treeWidget_folderList.setStyleSheet("")
        self.treeWidget_folderList.setAlternatingRowColors(True)
        self.treeWidget_folderList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidget_folderList.setHeaderHidden(True)
        self.treeWidget_folderList.setObjectName("treeWidget_folderList")
        # item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_folderList)
        # item_1 = QtWidgets.QTreeWidgetItem(item_0)
        # item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_folderList)
        # item_1 = QtWidgets.QTreeWidgetItem(item_0)
        # item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.scrollArea_pose = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea_pose.setWidgetResizable(True)
        self.scrollArea_pose.setObjectName("scrollArea_pose")
        self.scrollAreaWidget_pose = QtWidgets.QWidget()
        self.scrollAreaWidget_pose.setGeometry(QtCore.QRect(0, 0, 341, 580))
        self.scrollAreaWidget_pose.setObjectName("scrollAreaWidget_pose")
        self.gridLayout_poseList = QtWidgets.QGridLayout(self.scrollAreaWidget_pose)
        self.gridLayout_poseList.setObjectName("gridLayout_poseList")
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_poseList.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_poseList.addWidget(self.pushButton_10, 3, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_poseList.addWidget(self.pushButton_12, 3, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_poseList.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_poseList.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_poseList.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_poseList.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_poseList.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_poseList.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_poseList.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_poseList.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_poseList.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_poseList.addWidget(self.pushButton_13, 4, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_poseList.addWidget(self.pushButton_14, 4, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_poseList.addWidget(self.pushButton_15, 4, 2, 1, 1)
        self.scrollArea_pose.setWidget(self.scrollAreaWidget_pose)
        self.groupBox_pose = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_pose.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.groupBox_pose.setObjectName("groupBox_pose")
        self.verticalLayout_pose = QtWidgets.QVBoxLayout(self.groupBox_pose)
        self.verticalLayout_pose.setSpacing(10)
        self.verticalLayout_pose.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_pose.setObjectName("verticalLayout_pose")
        self.groupBox_snapShot = QtWidgets.QGroupBox(self.groupBox_pose)
        self.groupBox_snapShot.setObjectName("groupBox_snapShot")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_snapShot)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_snapShot = QtWidgets.QPushButton(self.groupBox_snapShot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_snapShot.sizePolicy().hasHeightForWidth())
        self.button_snapShot.setSizePolicy(sizePolicy)
        self.button_snapShot.setMinimumSize(QtCore.QSize(150, 150))
        self.button_snapShot.setObjectName("button_snapShot")
        self.horizontalLayout.addWidget(self.button_snapShot)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_pose.addWidget(self.groupBox_snapShot)
        self.groupBox_poseLabel = QtWidgets.QGroupBox(self.groupBox_pose)
        self.groupBox_poseLabel.setObjectName("groupBox_poseLabel")
        self.horizontalLayout_poseLabel = QtWidgets.QHBoxLayout(self.groupBox_poseLabel)
        self.horizontalLayout_poseLabel.setSpacing(5)
        self.horizontalLayout_poseLabel.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_poseLabel.setObjectName("horizontalLayout_poseLabel")
        self.label_poseLabel = QtWidgets.QLabel(self.groupBox_poseLabel)
        self.label_poseLabel.setObjectName("label_poseLabel")
        self.horizontalLayout_poseLabel.addWidget(self.label_poseLabel)
        self.lineEdit_poseLabel = QtWidgets.QLineEdit(self.groupBox_poseLabel)
        self.lineEdit_poseLabel.setObjectName("lineEdit_poseLabel")
        self.horizontalLayout_poseLabel.addWidget(self.lineEdit_poseLabel)
        self.verticalLayout_pose.addWidget(self.groupBox_poseLabel)
        self.textEdit_history = QtWidgets.QTextEdit(self.groupBox_pose)
        self.textEdit_history.setReadOnly(True)
        self.textEdit_history.setObjectName("textEdit_history")
        self.verticalLayout_pose.addWidget(self.textEdit_history)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_pose.addItem(spacerItem2)
        self.groupBox_blend = QtWidgets.QGroupBox(self.groupBox_pose)
        self.groupBox_blend.setObjectName("groupBox_blend")
        self.horizontalLayout_blend = QtWidgets.QHBoxLayout(self.groupBox_blend)
        self.horizontalLayout_blend.setSpacing(5)
        self.horizontalLayout_blend.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_blend.setObjectName("horizontalLayout_blend")
        self.slider_poseBlend = QtWidgets.QSlider(self.groupBox_blend)
        self.slider_poseBlend.setOrientation(QtCore.Qt.Horizontal)
        self.slider_poseBlend.setObjectName("slider_poseBlend")
        self.horizontalLayout_blend.addWidget(self.slider_poseBlend)
        self.button_blendValue = QtWidgets.QPushButton(self.groupBox_blend)
        self.button_blendValue.setMinimumSize(QtCore.QSize(50, 20))
        self.button_blendValue.setMaximumSize(QtCore.QSize(50, 20))
        self.button_blendValue.setStyleSheet("font: 12pt \"MS Sans Serif\";")
        self.button_blendValue.setObjectName("button_blendValue")
        self.horizontalLayout_blend.addWidget(self.button_blendValue)
        self.verticalLayout_pose.addWidget(self.groupBox_blend)
        self.button_save = QtWidgets.QPushButton(self.groupBox_pose)
        self.button_save.setObjectName("button_save")
        self.verticalLayout_pose.addWidget(self.button_save)
        self.horizontalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.action_create_folder = QtWidgets.QAction(MainWindow)
        self.action_create_folder.setObjectName("action_create_folder")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.treeWidget_folderList.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        __sortingEnabled = self.treeWidget_folderList.isSortingEnabled()
        self.treeWidget_folderList.setSortingEnabled(False)
        # self.treeWidget_folderList.topLevelItem(0).setText(0, QtWidgets.QApplication.translate("MainWindow", "A", None, -1))
        # self.treeWidget_folderList.topLevelItem(0).child(0).setText(0, QtWidgets.QApplication.translate("MainWindow", "01", None, -1))
        # self.treeWidget_folderList.topLevelItem(1).setText(0, QtWidgets.QApplication.translate("MainWindow", "B", None, -1))
        # self.treeWidget_folderList.topLevelItem(1).child(0).setText(0, QtWidgets.QApplication.translate("MainWindow", "01", None, -1))
        # self.treeWidget_folderList.topLevelItem(1).child(1).setText(0, QtWidgets.QApplication.translate("MainWindow", "02", None, -1))
        self.treeWidget_folderList.setSortingEnabled(__sortingEnabled)
        self.groupBox_pose.setTitle(QtWidgets.QApplication.translate("MainWindow", "Pose", None, -1))
        self.button_snapShot.setText(QtWidgets.QApplication.translate("MainWindow", "Icon", None, -1))
        self.label_poseLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Name", None, -1))
        self.button_blendValue.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.button_save.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.action_create_folder.setText(QtWidgets.QApplication.translate("MainWindow", "Create Folder", None, -1))

